name: Publish to VS Code Marketplace

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., v1.0.0, default: latest)'
        required: false
        type: string
        default: 'latest'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
        
    - name: Publish to VS Code Marketplace
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Install vsce
        pnpm add -g @vscode/vsce
        
        # Get version (default to latest)
        VERSION="${{ github.event.inputs.version || 'latest' }}"
        
        # Get release tag
        if [ "$VERSION" = "latest" ]; then
          RELEASE_TAG=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
        else
          RELEASE_TAG="$VERSION"
        fi
        
        echo "Publishing release: $RELEASE_TAG"
        
        # Find and download the .vsix file
        VSIX_FILE=$(gh release view "$RELEASE_TAG" --json assets --jq '.assets[] | select(.name | contains(".vsix")) | .name' | head -n1)
        echo "Found .vsix file: $VSIX_FILE"
        
        gh release download "$RELEASE_TAG" --pattern "$VSIX_FILE"
        
        # Publish to marketplace
        echo "🚀 Publishing $VSIX_FILE to VS Code Marketplace..."
        vsce publish --packagePath "$VSIX_FILE"
        
        echo "✅ Successfully published $VSIX_FILE to VS Code Marketplace!"
