name: Publish to VS Code Marketplace

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to publish (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Get release tag
      id: release-tag
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ "${{ github.event_name }}" = "release" ]; then
          RELEASE_TAG="${{ github.event.release.tag_name }}"
        else
          RELEASE_TAG="${{ github.event.inputs.release_tag }}"
        fi
        echo "release-tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
        echo "Publishing release: $RELEASE_TAG"
        
        # Debug: Check token permissions and list releases
        echo "Checking GitHub CLI authentication..."
        gh auth status
        
        echo "Available releases:"
        gh release list --limit 5 || echo "Failed to list releases"
        
        
    - name: Publish to VS Code Marketplace
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Install vsce
        npm install -g @vscode/vsce
        
        # Get release tag
        RELEASE_TAG="${{ steps.release-tag.outputs.release-tag }}"
        
        # Find the .vsix file in release assets
        VSIX_FILE=$(gh release view "$RELEASE_TAG" --json assets --jq '.assets[] | select(.name | contains(".vsix")) | .name' | head -n1)
        
        # Download the .vsix file
        gh release download "$RELEASE_TAG" --pattern "$VSIX_FILE"
        
        # Publish to marketplace
        echo "🚀 Publishing $VSIX_FILE to VS Code Marketplace..."
        vsce publish --packagePath "$VSIX_FILE"
        
        echo "✅ Successfully published $VSIX_FILE to VS Code Marketplace!"
        
    - name: Update release notes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        RELEASE_TAG="${{ steps.release-tag.outputs.release-tag }}"
        
        # Add marketplace link to release notes
        MARKETPLACE_URL="https://marketplace.visualstudio.com/items?itemName=wojciechciok.azure-queue-storage-explorer"
        
        # Get current release body
        CURRENT_BODY=$(gh release view "$RELEASE_TAG" --json body --jq '.body')
        
        # Add marketplace link if not already present
        if ! echo "$CURRENT_BODY" | grep -q "marketplace.visualstudio.com"; then
          NEW_BODY="$CURRENT_BODY"$'\n\n'"## 📦 VS Code Marketplace"$'\n'"[Install from VS Code Marketplace]($MARKETPLACE_URL)"
          
          gh release edit "$RELEASE_TAG" --notes "$NEW_BODY"
          echo "✅ Updated release notes with marketplace link"
        fi
